#!/bin/sh

set -eu
export LC_ALL=C

BASE_URL='https://raw.githubusercontent.com/hectorm/docker-compose-helpers/master'
INSTALL_DIR=/usr/local/bin

curl \
	--proto '=https' --tlsv1.2 \
	--output "${INSTALL_DIR:?}/docker-compose-#1" \
	"${BASE_URL:?}/docker-compose-{logs,restart,start,stop,upgrade,helpers-upgrade}"

chown root:root "${INSTALL_DIR:?}"/docker-compose-*
chmod 755 "${INSTALL_DIR:?}"/docker-compose-*
