#!/bin/sh

set -eu
export LC_ALL=C

DOCKER_COMPOSE_CMD=/usr/local/bin/docker-compose

DOCKER_COMPOSE_TMPDIR=$(mktemp -d)
trap 'rm -rf "${DOCKER_COMPOSE_TMPDIR:?}"' EXIT

DOCKER_COMPOSE_BINARY_NAME=docker-compose-$(uname -s)-$(uname -m)
DOCKER_COMPOSE_BINARY_URL=$(curl --proto '=https' --tlsv1.2 -fsSL 'https://api.github.com/repos/docker/compose/releases/latest' \
	| grep -om1 "https://github.com/docker/compose/releases/download/[0-9]*\.[0-9]*\.[0-9]*/${DOCKER_COMPOSE_BINARY_NAME:?}")

curl --proto '=https' --tlsv1.2 -L "${DOCKER_COMPOSE_BINARY_URL:?}" -o "${DOCKER_COMPOSE_TMPDIR:?}/${DOCKER_COMPOSE_BINARY_NAME:?}"
curl --proto '=https' --tlsv1.2 -L "${DOCKER_COMPOSE_BINARY_URL:?}.sha256" -o "${DOCKER_COMPOSE_TMPDIR:?}/${DOCKER_COMPOSE_BINARY_NAME:?}.sha256"

(cd "${DOCKER_COMPOSE_TMPDIR:?}" && sha256sum -c "${DOCKER_COMPOSE_BINARY_NAME:?}.sha256" || exit 1)

mv -fv "${DOCKER_COMPOSE_TMPDIR:?}/${DOCKER_COMPOSE_BINARY_NAME:?}" "${DOCKER_COMPOSE_CMD:?}"
chown root:root "${DOCKER_COMPOSE_CMD:?}"
chmod 755 "${DOCKER_COMPOSE_CMD:?}"

"${DOCKER_COMPOSE_CMD:?}" --version
